spring.application.name=event-driven-order-system
spring.jpa.show-sql=false
logging.level.org.springframework.cache=TRACE
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=WARN
logging.level.org.apache.kafka.clients.producer.ProducerConfig=WARN
logging.level.org.apache.kafka.clients.admin.AdminClientConfig=WARN
logging.level.org.apache.kafka.common.utils.AppInfoParser=WARN